name: AsherWars
version: '1.0-SNAPSHOT'
main: org.auriosi.asherWars.AsherWars
api-version: '1.21'
depend: [ ProtocolLib ]
commands:
  start:
    description: Start the game
    usage: /start
  jointeam:
    description: Join a team
    usage: /jointeam <team>
    aliases: [
      jt
    ]